config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:show, :new, :destroy, :create, :update, :index, :edit, :delete] 
  resources :pictures
  resources :charges, only: [:new, :create]
  root to: 'store#index' 
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/users/sign_out',  to: 'devise/sessions#destroy'
  get '/users/sign_out' => :destroy, to: 'sessions#new'
  get 'products/index' => :destroy, to: 'products#index'
  get "/products", to: "products#index"
  post "/products", to: "products#create"
  get "/products/:id/edit", to: "products#edit"
  put "/products/:id", to: "products#update"
  patch "/products/:id", to: "products#update"
  get "/products/:id", to: "products#show"
  delete "/products/:id", to: "products#destroy"
  get "/products/:id" => :destroy, to: "products#index"
  get "/payments/success", to: "payments#success"
  get "/payment", to: "pages#payment", as: "payment"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user, :optional => true
    belongs_to :buyer, :optional => true
    belongs_to :seller, :optional => true
    has_many_attached :image_urls
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
  has_many :products
  has_many_attached :image_urls
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    
end
    #if not authenticated or logged in user cannot view shop

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def success
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update delete destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def update
    @product = Product.find(params[:id])
    @product_id = @product.id 
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
 

  # POST /products or /products.json
  def create
    @product = Product.create(product_params)
    @product_id = @product.id 
    respond_to do |format|
        if @product.save 
          format.html {redirect_to @product, notice: "Product was successfully listed." }
          format.json {render :show, status: :created, location: @product}
        else
          format.json {render json: @product.errors, status: :unprocessable_entity }
        end
    end
  end



  # Allows product to be deleted and then redirects to index page of shop
  def destroy
    @product = Product.find(params[:id]).delete
    respond_to do |format|
        if @product.delete
          format.html {redirect_to @product, notice: "Product was successfully deleted." }
        else
          format.json {render json: @product.errors, status: :unprocessable_entity }
        end
    end
  end

 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def set_products
      @products = Product.all
    end
  
    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :category, :image_url, :buyer_id, :seller_id)
    end
  

    #stripe payment feature 
    def generate_stripe_session
      session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      customer_email: current_user.email,
      line_items: [{
          name: @product.title,
          description: @product.description,
          amount: @product.price,
          currency: 'aud',
          quantity: 1,
      }],
      payment_intent_data: {
          metadata: {
              user_id: current_user.id,
              product_id: @product.id
          }
      },
      success_url: "#{root_url}payments/success?productId=#{product.id}",
      cancel_url: "#{root_url}products"
    )

    @session_id = session.id
    end

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StreetwearApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "partials/navbar"%>
  <div class="container">
  <p class="notice"><%= notice %></p>
    <%= yield %>
  </div>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
  <div class="container-fluid">
    <a class="navbar-brand"  href="/">Unscr!pted</a>
    <button class="navbar-toggler p-0 border-0" type="button" id="navbarSideCollapse" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    <nav class="nav nav-masthead justify-content-center float-md-end">
    <div class="authorisation buttons">
    <% if user_signed_in?%>
    <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-dark" %>
    <% else %>
    <%= button_to "Log In", new_user_session_path, :method => :get, class: "btn btn-dark" %>
    <%end%>
    </div>
    <div>
    <% if user_signed_in?%>
    <%= button_to "Account", edit_user_registration_path, method: :get, class: "btn btn-dark" %>
    <%end%>
    </div>
    <div>
    <% if user_signed_in?%>
    <%= button_to "Shop", products_path, method: :get, class: "btn btn-dark" %>
    <%end%>
    </div>
  </nav>
</nav>

app/views/payments/success.html.erb
You have successfully made a payment!
<%= link_to "Go to Products", products_path %>

# user is redirected here when payment is made

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <%end%>
  
  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :category, collection: ["footwear", "accessories", "menswear", "womenswear"] %>
    <%= f.file_field :image_url, multiple: false, accept: 'image/png, image/jpg, image/jpeg' %>
    <%= f.submit %>
    <br>
    <%= link_to 'Back', products_path %>
  </div>
<%end%>

app/views/products/edit.html.erb
<%= simple_form_for product_path, url: {action: "update"} do |f| %>
    <h1 class="heading">Edit Product</h1>
    <%= render 'form', product: @product %>
<% end %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">


<h1>Products</h1>
<%= link_to "New Product", new_product_path, method: :get %>
    <div class="card-deck">
    <% @products.each do |product| %>
        <div class="card" style="width: 18rem; max-height: 50%; ">
          <% if product.image_url %>
            <%= image_tag product.image_url %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= product.title %>
            <h6 class="card-subtitle mb-2 text-muted"><%= product.description %>
            <p class="card-text mt-2"><%= product.price %>
            <p class="card-text"><small class="text-muted"><%= product.category %>
            <br>
            <strong><%= link_to 'Show', product_path(product), method: :show %></td><strong>
            <strong><%= link_to 'Edit', edit_product_path(product), method: :edit %></td></strong>
            <%= button_to 'Delete', product_path(product), :method => :delete %></td>
          </div>
        </div>
    <% end %>
    </div>
</div>

app/views/products/new.html.erb
<%= simple_form_for new_product_path, url: {action: "create"} do |f| %>
    <h1 class="heading">New Product</h1>
    <%= render 'form', product: @product %>
<% end %>

app/views/products/show.html.erb
<main>

<br>
<br>
<br>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<button data-stripe="payment", class="btn btn-sm btn-outline-secondary">Purchase</button>
<br>
<%= link_to 'Edit', edit_product_path(@product) %> 
<%= link_to 'Back', products_path %>


<div class="card mb-4" style="max-width: 25rem;">
<% if @product.image_url %>
  <%= image_tag @product.image_url %>
<% end %>
</div>

<br>

</main>


<script src="https://js.stripe.com/v3/"></script>

<script>
  document
    .querySelector("[data-stripe='payment']")
    .addEventListener("click", () => {
      const stripe = Stripe(
        "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
      );

      stripe.redirectToCheckout({
        sessionId: "<%= @session_id %>"
      });
    });
</script>

app/views/store/index.html.erb
<html lang="en" class="h-100"><head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.87.0">
  <title>Cover Template · Bootstrap v5.1</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/cover/">


  <!-- Bootstrap core CSS -->
<link href="/docs/5.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">



<main class="px-3">
  <h1>Find your perfect kicks today</h1>
  <br></br>
  <p class="lead">Buy and sell only the most coveted pieces at Unscr!pted, Australias leading underground streetwear marketplace.</p>
  <br></br>
  <p class="lead">
    <% if user_signed_in?%>
    <%= link_to "Start Browsing", products_path, method: :get, class: "nav-link" %>
    <% else %>
    <%= link_to "Log In", new_user_session_path, method: :get, class: "nav-link" %>
    <%end%>
  </p>
</main>


<footer class="mt-auto text-white-50">
    <p>&copy; Unscr!pted Worldw!de 2021</p>
  </footer>
</div>